FROM python:latest
  2
  3 WORKDIR /app
  4 COPY . /app
  5 
  6 RUN apt-get update && apt-get upgrade -y && apt-get install -y python3-tk xvfb && rm -rf /var/lib/apt/lists/*
  7 
  8 EXPOSE 5000
  9 CMD xvfb-run python hello.py